// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learnly.Repository.Migrations
{
    [DbContext(typeof(LearnlyContexto))]
    [Migration("20260120124843_Procedures")]
    partial class Procedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventoEstudo", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventoId"));

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("EventoId");

                    b.HasIndex("PlanoId");

                    b.ToTable("EventosEstudo", (string)null);
                });

            modelBuilder.Entity("Learnly.Domain.Entities.PlanoEstudo", b =>
                {
                    b.Property<int>("PlanoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasPorSemana")
                        .HasColumnType("int");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PlanoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PlanosEstudo", (string)null);
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Planos.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<string>("Cor")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Planos.PlanoMateria", b =>
                {
                    b.Property<int>("PlanoMateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanoMateriaId"));

                    b.Property<int>("HorasConcluidas")
                        .HasColumnType("int");

                    b.Property<int>("HorasTotais")
                        .HasColumnType("int");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.HasKey("PlanoMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PlanoId");

                    b.ToTable("PlanoMaterias", (string)null);
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Simulados.Alternativa", b =>
                {
                    b.Property<int>("AlternativaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlternativaId"));

                    b.Property<string>("Arquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Correta")
                        .HasColumnType("bit");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlternativaId");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Alternativas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Alternativa_TextoOuArquivo", "Texto IS NOT NULL OR Arquivo IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Simulados.RespostaSimulado", b =>
                {
                    b.Property<int>("RespostaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RespostaId"));

                    b.Property<int>("AlternativaId")
                        .HasColumnType("int");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<int>("SimuladoId")
                        .HasColumnType("int");

                    b.HasKey("RespostaId");

                    b.HasIndex("AlternativaId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("SimuladoId");

                    b.ToTable("RespostasSimulado", (string)null);
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Simulados.SimuladoQuestao", b =>
                {
                    b.Property<int>("SimuladoQuestaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SimuladoQuestaoId"));

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.Property<int>("SimuladoId")
                        .HasColumnType("int");

                    b.HasKey("SimuladoQuestaoId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("SimuladoId");

                    b.ToTable("SimuladoQuestoes", (string)null);
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusConta")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Questao", b =>
                {
                    b.Property<int>("QuestaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestaoId"));

                    b.Property<string>("AlternativaCorreta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Arquivos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contexto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IntroducaoAlternativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lingua")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("QuestaoId");

                    b.ToTable("Questoes", (string)null);
                });

            modelBuilder.Entity("Simulado", b =>
                {
                    b.Property<int>("SimuladoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SimuladoId"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SimuladoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Simulados", (string)null);
                });

            modelBuilder.Entity("EventoEstudo", b =>
                {
                    b.HasOne("Learnly.Domain.Entities.PlanoEstudo", "Plano")
                        .WithMany("Agenda")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.PlanoEstudo", b =>
                {
                    b.HasOne("Learnly.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PlanoEstudo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Planos.PlanoMateria", b =>
                {
                    b.HasOne("Learnly.Domain.Entities.Planos.Materia", "Materia")
                        .WithMany("PlanoMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnly.Domain.Entities.PlanoEstudo", "Plano")
                        .WithMany("PlanoMaterias")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Simulados.Alternativa", b =>
                {
                    b.HasOne("Questao", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Simulados.RespostaSimulado", b =>
                {
                    b.HasOne("Learnly.Domain.Entities.Simulados.Alternativa", "Alternativa")
                        .WithMany()
                        .HasForeignKey("AlternativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Questao", "Questao")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Simulado", "Simulado")
                        .WithMany("Respostas")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alternativa");

                    b.Navigation("Questao");

                    b.Navigation("Simulado");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Simulados.SimuladoQuestao", b =>
                {
                    b.HasOne("Questao", "Questao")
                        .WithMany("Simulados")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Simulado", "Simulado")
                        .WithMany("Questoes")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Simulado");
                });

            modelBuilder.Entity("Simulado", b =>
                {
                    b.HasOne("Learnly.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Simulados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Learnly.Domain.Entities.Simulados.DesempenhoSimulado", "Desempenho", b1 =>
                        {
                            b1.Property<int>("SimuladoId")
                                .HasColumnType("int");

                            b1.Property<string>("Feedback")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("QuantidadeDeAcertos")
                                .HasColumnType("int");

                            b1.Property<int>("QuantidadeDeQuestoes")
                                .HasColumnType("int");

                            b1.HasKey("SimuladoId");

                            b1.ToTable("Simulados");

                            b1.WithOwner()
                                .HasForeignKey("SimuladoId");
                        });

                    b.Navigation("Desempenho");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.PlanoEstudo", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("PlanoMaterias");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Planos.Materia", b =>
                {
                    b.Navigation("PlanoMaterias");
                });

            modelBuilder.Entity("Learnly.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("PlanoEstudo");

                    b.Navigation("Simulados");
                });

            modelBuilder.Entity("Questao", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Respostas");

                    b.Navigation("Simulados");
                });

            modelBuilder.Entity("Simulado", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
